<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IndustrySeeder extends Seeder
{
    public function run()
    {
        DB::table('industries')->truncate();
        $data = [];
        $data[] = ['id' => 151, 'name' => 'Acai Bowl Shop'];
        $data[] = ['id' => 20, 'name' => 'Accounting and Tax Preparation'];
        $data[] = ['id' => 153, 'name' => 'Adult Entertainment '];
        $data[] = ['id' => 152, 'name' => 'Advertising'];
        $data[] = ['id' => 21, 'name' => 'Advertising, Marketing and PR'];
        $data[] = ['id' => 138, 'name' => 'Aerospace Industries'];
        $data[] = ['id' => 94, 'name' => 'Agricultural Services'];
        $data[] = ['id' => 1, 'name' => 'Agriculture and Mining other'];
        $data[] = ['id' => 137, 'name' => 'Airport Parking Service'];
        $data[] = ['id' => 22, 'name' => 'Alcoholic Beverages'];
        $data[] = ['id' => 23, 'name' => 'Alternative Energy Sources'];
        $data[] = ['id' => 135, 'name' => 'Ambulance Service'];
        $data[] = ['id' => 130, 'name' => 'Amusement Parks'];
        $data[] = ['id' => 105, 'name' => 'Animal Hospitals'];
        $data[] = ['id' => 147, 'name' => 'Animal Shelters'];
        $data[] = ['id' => 110, 'name' => 'Art Galleries &amp; Dealers'];
        $data[] = ['id' => 216, 'name' => 'Auctions'];
        $data[] = ['id' => 24, 'name' => 'Audio, Video and Photography'];
        $data[] = ['id' => 154, 'name' => 'Auto Body/Repair Shop'];
        $data[] = ['id' => 19, 'name' => 'Auto repair'];
        $data[] = ['id' => 122, 'name' => 'Automobile Dealers-new Cars'];
        $data[] = ['id' => 127, 'name' => 'Automobile Dealers-used Cars'];
        $data[] = ['id' => 25, 'name' => 'Automobiles, Boats and Motor Vehicles'];
        $data[] = ['id' => 26, 'name' => 'Automotive Sales'];
        $data[] = ['id' => 155, 'name' => 'Bakery'];
        $data[] = ['id' => 124, 'name' => 'Bars'];
        $data[] = ['id' => 205, 'name' => 'Billing'];
        $data[] = ['id' => 27, 'name' => 'Biotechnology'];
        $data[] = ['id' => 136, 'name' => 'Boat Dealers Sales &amp; Service'];
        $data[] = ['id' => 157, 'name' => 'Bowling Alley'];
        $data[] = ['id' => 156, 'name' => 'Brewery'];
        $data[] = ['id' => 2, 'name' => 'Business Services'];
        $data[] = ['id' => 116, 'name' => 'Cabinet Makers'];
        $data[] = ['id' => 143, 'name' => 'Call Centers'];
        $data[] = ['id' => 148, 'name' => 'Campgrounds'];
        $data[] = ['id' => 158, 'name' => 'Car Rental'];
        $data[] = ['id' => 145, 'name' => 'Car Service'];
        $data[] = ['id' => 142, 'name' => 'Carpenters'];
        $data[] = ['id' => 118, 'name' => 'Carwashes'];
        $data[] = ['id' => 141, 'name' => 'Casinos'];
        $data[] = ['id' => 161, 'name' => 'Catering'];
        $data[] = ['id' => 160, 'name' => 'Cell Phone Stores'];
        $data[] = ['id' => 28, 'name' => 'Chemicals and Petrochemicals'];
        $data[] = ['id' => 123, 'name' => 'Coffee Shops'];
        $data[] = ['id' => 95, 'name' => 'Communications'];
        $data[] = ['id' => 3, 'name' => 'Computer and Electronics'];
        $data[] = ['id' => 163, 'name' => 'Computer Software/ Repair'];
        $data[] = ['id' => 29, 'name' => 'Computers, Parts and Repair'];
        $data[] = ['id' => 30, 'name' => 'Concrete, Glass and Building Materials'];
        $data[] = ['id' => 17, 'name' => 'Construction'];
        $data[] = ['id' => 159, 'name' => 'Construction/ Contracting'];
        $data[] = ['id' => 162, 'name' => 'Consulting'];
        $data[] = ['id' => 31, 'name' => 'Consumer Electronics, Parts and Repair'];
        $data[] = ['id' => 4, 'name' => 'Consumer Services'];
        $data[] = ['id' => 208, 'name' => 'Convenience Store '];
        $data[] = ['id' => 164, 'name' => 'Copying/ Printing'];
        $data[] = ['id' => 195, 'name' => 'Cosmetics'];
        $data[] = ['id' => 166, 'name' => 'Dance Studio'];
        $data[] = ['id' => 33, 'name' => 'Data and Records Management'];
        $data[] = ['id' => 165, 'name' => 'Day Care'];
        $data[] = ['id' => 168, 'name' => 'Deli'];
        $data[] = ['id' => 167, 'name' => 'Dentist/ Dental Labs'];
        $data[] = ['id' => 34, 'name' => 'Diagnostic Laboratories'];
        $data[] = ['id' => 213, 'name' => 'Distribution '];
        $data[] = ['id' => 35, 'name' => 'Doctors and Health Care Practitioners'];
        $data[] = ['id' => 133, 'name' => 'E-commerce'];
        $data[] = ['id' => 5, 'name' => 'Education'];
        $data[] = ['id' => 109, 'name' => 'Electric Contractors'];
        $data[] = ['id' => 170, 'name' => 'Electronic Sales'];
        $data[] = ['id' => 36, 'name' => 'Elementary and Secondary Schools'];
        $data[] = ['id' => 117, 'name' => 'Elevators-sales &amp; Service'];
        $data[] = ['id' => 114, 'name' => 'Employment Agencies'];
        $data[] = ['id' => 6, 'name' => 'Energy and Utilities'];
        $data[] = ['id' => 96, 'name' => 'Engineering'];
        $data[] = ['id' => 198, 'name' => 'Entertainment'];
        $data[] = ['id' => 199, 'name' => 'Equipment '];
        $data[] = ['id' => 111, 'name' => 'Excavation Work'];
        $data[] = ['id' => 37, 'name' => 'Facilities Management and Maintenance'];
        $data[] = ['id' => 171, 'name' => 'Factory'];
        $data[] = ['id' => 38, 'name' => 'Farming and Mining Machinery and Equipment'];
        $data[] = ['id' => 39, 'name' => 'Farming and Ranching'];
        $data[] = ['id' => 172, 'name' => 'Farming/ Farming Supplies'];
        $data[] = ['id' => 215, 'name' => 'Financial / Investors'];
        $data[] = ['id' => 7, 'name' => 'Financial Services'];
        $data[] = ['id' => 176, 'name' => 'Firearm Sales'];
        $data[] = ['id' => 40, 'name' => 'Fishing, Hunting and Forestry and Logging'];
        $data[] = ['id' => 131, 'name' => 'Flea Markets'];
        $data[] = ['id' => 121, 'name' => 'Florists'];
        $data[] = ['id' => 41, 'name' => 'Food and Dairy Product Manufacturing and Packaging'];
        $data[] = ['id' => 175, 'name' => 'Frozen Yogurt/ Ice Cream Shops'];
        $data[] = ['id' => 174, 'name' => 'Fuel Dealers'];
        $data[] = ['id' => 173, 'name' => 'Funeral Homes'];
        $data[] = ['id' => 42, 'name' => 'Funeral Homes and Services'];
        $data[] = ['id' => 43, 'name' => 'Furniture Manufacturing'];
        $data[] = ['id' => 107, 'name' => 'Furniture Stores'];
        $data[] = ['id' => 177, 'name' => 'Gas Station'];
        $data[] = ['id' => 44, 'name' => 'Gasoline and Oil Refineries'];
        $data[] = ['id' => 104, 'name' => 'Gift Shops'];
        $data[] = ['id' => 106, 'name' => 'Golf Courses'];
        $data[] = ['id' => 212, 'name' => 'Government Agency'];
        $data[] = ['id' => 126, 'name' => 'Graphic Designers'];
        $data[] = ['id' => 108, 'name' => 'Grocery Stores'];
        $data[] = ['id' => 128, 'name' => 'Gymnasiums'];
        $data[] = ['id' => 113, 'name' => 'Hardware Stores'];
        $data[] = ['id' => 8, 'name' => 'Health, Pharmaceuticals, and Biotech'];
        $data[] = ['id' => 204, 'name' => 'Healthcare Services'];
        $data[] = ['id' => 178, 'name' => 'Home Health Care/ Hospice'];
        $data[] = ['id' => 45, 'name' => 'Hospitals'];
        $data[] = ['id' => 112, 'name' => 'Hotels And Motels'];
        $data[] = ['id' => 46, 'name' => 'HR and Recruiting Services'];
        $data[] = ['id' => 140, 'name' => 'Ice-manufacturers'];
        $data[] = ['id' => 103, 'name' => 'Import / Export'];
        $data[] = ['id' => 92, 'name' => 'Insurance'];
        $data[] = ['id' => 47, 'name' => 'IT and Network Services and Support'];
        $data[] = ['id' => 200, 'name' => 'IT Services'];
        $data[] = ['id' => 179, 'name' => 'Janitorial'];
        $data[] = ['id' => 115, 'name' => 'Jewelry Stores'];
        $data[] = ['id' => 180, 'name' => 'Landscaping/ Masonry'];
        $data[] = ['id' => 181, 'name' => 'Laundromat'];
        $data[] = ['id' => 48, 'name' => 'Laundry and Dry Cleaning'];
        $data[] = ['id' => 49, 'name' => 'Legal Services'];
        $data[] = ['id' => 50, 'name' => 'Lending and Mortgage'];
        $data[] = ['id' => 51, 'name' => 'Libraries, Archives and Museums'];
        $data[] = ['id' => 102, 'name' => 'Liquor Stores'];
        $data[] = ['id' => 129, 'name' => 'Livestock'];
        $data[] = ['id' => 214, 'name' => 'Locksmith'];
        $data[] = ['id' => 119, 'name' => 'Logging'];
        $data[] = ['id' => 146, 'name' => 'Maid &amp; Butler Service'];
        $data[] = ['id' => 52, 'name' => 'Management Consulting'];
        $data[] = ['id' => 9, 'name' => 'Manufacturing'];
        $data[] = ['id' => 182, 'name' => 'Marijuana '];
        $data[] = ['id' => 194, 'name' => 'Marketing'];
        $data[] = ['id' => 10, 'name' => 'Media and Entertainment'];
        $data[] = ['id' => 53, 'name' => 'Medical Devices'];
        $data[] = ['id' => 183, 'name' => 'Medical Office/ Services'];
        $data[] = ['id' => 54, 'name' => 'Medical Supplies and Equipment'];
        $data[] = ['id' => 55, 'name' => 'Metals Manufacturing'];
        $data[] = ['id' => 139, 'name' => 'MFRS'];
        $data[] = ['id' => 56, 'name' => 'Mining and Quarrying'];
        $data[] = ['id' => 144, 'name' => 'Motorcycle Dealers'];
        $data[] = ['id' => 184, 'name' => 'Motorcycle Sales/ Service'];
        $data[] = ['id' => 99, 'name' => 'Nail Salon'];
        $data[] = ['id' => 57, 'name' => 'Network Security Products'];
        $data[] = ['id' => 58, 'name' => 'Networking equipment and Systems'];
        $data[] = ['id' => 134, 'name' => 'Night Clubs'];
        $data[] = ['id' => 211, 'name' => 'Non-Profit Organization'];
        $data[] = ['id' => 59, 'name' => 'Nonalcoholic Beverages'];
        $data[] = ['id' => 185, 'name' => 'Notary'];
        $data[] = ['id' => 60, 'name' => 'Office Machinery and Equipment'];
        $data[] = ['id' => 61, 'name' => 'Outpatient Care Centers'];
        $data[] = ['id' => 150, 'name' => 'Painting'];
        $data[] = ['id' => 62, 'name' => 'Paper and Paper Products'];
        $data[] = ['id' => 63, 'name' => 'Parking Lots and Garage Management'];
        $data[] = ['id' => 186, 'name' => 'Pawn Shops'];
        $data[] = ['id' => 64, 'name' => 'Payroll Services'];
        $data[] = ['id' => 65, 'name' => 'Personal Financial Planning and Private Banking'];
        $data[] = ['id' => 66, 'name' => 'Personal Health Care Products'];
        $data[] = ['id' => 132, 'name' => 'Pest Control'];
        $data[] = ['id' => 67, 'name' => 'Pharmaceuticals'];
        $data[] = ['id' => 207, 'name' => 'Pharmacy '];
        $data[] = ['id' => 68, 'name' => 'Plastics and Rubber Manufacturing'];
        $data[] = ['id' => 187, 'name' => 'Property Management '];
        $data[] = ['id' => 201, 'name' => 'Real Estate'];
        $data[] = ['id' => 11, 'name' => 'Real Estate and Construction'];
        $data[] = ['id' => 203, 'name' => 'Recycling Center'];
        $data[] = ['id' => 206, 'name' => 'Religious Center'];
        $data[] = ['id' => 188, 'name' => 'Rentals/ Air BNB'];
        $data[] = ['id' => 69, 'name' => 'Residential and Long-term Care Facilities'];
        $data[] = ['id' => 93, 'name' => 'Restaurant'];
        $data[] = ['id' => 18, 'name' => 'Retail'];
        $data[] = ['id' => 70, 'name' => 'Retail - apparel &amp; accessory Stores'];
        $data[] = ['id' => 71, 'name' => 'Retail - Auto Dealers &amp; Gasoline Stations'];
        $data[] = ['id' => 72, 'name' => 'Retail - Computer &amp; Computer software sales'];
        $data[] = ['id' => 73, 'name' => 'Retail - Convenience stores'];
        $data[] = ['id' => 74, 'name' => 'Retail - Drug Stores'];
        $data[] = ['id' => 75, 'name' => 'Retail - Eating &amp; Drinking Places'];
        $data[] = ['id' => 76, 'name' => 'Retail - Furniture Stores'];
        $data[] = ['id' => 77, 'name' => 'Retail - Grocery Stores'];
        $data[] = ['id' => 78, 'name' => 'Retail - Jewelry Stores'];
        $data[] = ['id' => 79, 'name' => 'Retail - Mobile Home Dealers'];
        $data[] = ['id' => 80, 'name' => 'Retail - Restaurants '];
        $data[] = ['id' => 81, 'name' => 'Retail - Retail Stores'];
        $data[] = ['id' => 82, 'name' => 'Sales Services'];
        $data[] = ['id' => 191, 'name' => 'Salons/ Spas'];
        $data[] = ['id' => 189, 'name' => 'Security'];
        $data[] = ['id' => 83, 'name' => 'Security Services'];
        $data[] = ['id' => 84, 'name' => 'Semiconductor and Microchip Manufacturing'];
        $data[] = ['id' => 12, 'name' => 'Software and Internet'];
        $data[] = ['id' => 190, 'name' => 'Solar'];
        $data[] = ['id' => 85, 'name' => 'Sports, Arts, and Recreation Instruction'];
        $data[] = ['id' => 192, 'name' => 'Tax &amp; Accounting'];
        $data[] = ['id' => 86, 'name' => 'Technical and Trade Schools'];
        $data[] = ['id' => 13, 'name' => 'Telecommunications'];
        $data[] = ['id' => 125, 'name' => 'Telecommunications Services'];
        $data[] = ['id' => 87, 'name' => 'Test Preparation'];
        $data[] = ['id' => 88, 'name' => 'Textiles, Apparel and Accessories'];
        $data[] = ['id' => 89, 'name' => 'Tools, Hardware and Light Machinery'];
        $data[] = ['id' => 101, 'name' => 'Towing'];
        $data[] = ['id' => 197, 'name' => 'Transportation'];
        $data[] = ['id' => 14, 'name' => 'Transportation and Storage'];
        $data[] = ['id' => 209, 'name' => 'Travel Agency'];
        $data[] = ['id' => 15, 'name' => 'Travel Recreation and Leisure'];
        $data[] = ['id' => 193, 'name' => 'Trucking/ Logistics'];
        $data[] = ['id' => 202, 'name' => 'Vape/ Smoke shop'];
        $data[] = ['id' => 90, 'name' => 'Veterinary Clinics and Services'];
        $data[] = ['id' => 120, 'name' => 'Warehouses'];
        $data[] = ['id' => 210, 'name' => 'Waste Management / Junk Removal'];
        $data[] = ['id' => 91, 'name' => 'Waste Management and Recycling'];
        $data[] = ['id' => 16, 'name' => 'Wholesale and Distribution'];
        DB::table('industries')->insert($data);
    }
}
